//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace PRACTIK2.IPC2 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://www.practica2.com")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback insert_aerolineOperationCompleted;
        
        private System.Threading.SendOrPostCallback insert_avionOperationCompleted;
        
        private System.Threading.SendOrPostCallback insert_reservacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback insert_clienteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::PRACTIK2.Properties.Settings.Default.PRACTIK2_IPC2_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event insert_aerolineCompletedEventHandler insert_aerolineCompleted;
        
        /// <remarks/>
        public event insert_avionCompletedEventHandler insert_avionCompleted;
        
        /// <remarks/>
        public event insert_reservacionCompletedEventHandler insert_reservacionCompleted;
        
        /// <remarks/>
        public event insert_clienteCompletedEventHandler insert_clienteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.practica2.com/insert_aeroline", RequestNamespace="http://www.practica2.com", ResponseNamespace="http://www.practica2.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string insert_aeroline(string id_aerolinea, string nombre, string telefono, string direccion) {
            object[] results = this.Invoke("insert_aeroline", new object[] {
                        id_aerolinea,
                        nombre,
                        telefono,
                        direccion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void insert_aerolineAsync(string id_aerolinea, string nombre, string telefono, string direccion) {
            this.insert_aerolineAsync(id_aerolinea, nombre, telefono, direccion, null);
        }
        
        /// <remarks/>
        public void insert_aerolineAsync(string id_aerolinea, string nombre, string telefono, string direccion, object userState) {
            if ((this.insert_aerolineOperationCompleted == null)) {
                this.insert_aerolineOperationCompleted = new System.Threading.SendOrPostCallback(this.Oninsert_aerolineOperationCompleted);
            }
            this.InvokeAsync("insert_aeroline", new object[] {
                        id_aerolinea,
                        nombre,
                        telefono,
                        direccion}, this.insert_aerolineOperationCompleted, userState);
        }
        
        private void Oninsert_aerolineOperationCompleted(object arg) {
            if ((this.insert_aerolineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insert_aerolineCompleted(this, new insert_aerolineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.practica2.com/insert_avion", RequestNamespace="http://www.practica2.com", ResponseNamespace="http://www.practica2.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string insert_avion(string id_avion, string capacidad, string peso, string id_aero) {
            object[] results = this.Invoke("insert_avion", new object[] {
                        id_avion,
                        capacidad,
                        peso,
                        id_aero});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void insert_avionAsync(string id_avion, string capacidad, string peso, string id_aero) {
            this.insert_avionAsync(id_avion, capacidad, peso, id_aero, null);
        }
        
        /// <remarks/>
        public void insert_avionAsync(string id_avion, string capacidad, string peso, string id_aero, object userState) {
            if ((this.insert_avionOperationCompleted == null)) {
                this.insert_avionOperationCompleted = new System.Threading.SendOrPostCallback(this.Oninsert_avionOperationCompleted);
            }
            this.InvokeAsync("insert_avion", new object[] {
                        id_avion,
                        capacidad,
                        peso,
                        id_aero}, this.insert_avionOperationCompleted, userState);
        }
        
        private void Oninsert_avionOperationCompleted(object arg) {
            if ((this.insert_avionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insert_avionCompleted(this, new insert_avionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.practica2.com/insert_reservacion", RequestNamespace="http://www.practica2.com", ResponseNamespace="http://www.practica2.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string insert_reservacion(string id_reserva, string destino, string fecha, string precio) {
            object[] results = this.Invoke("insert_reservacion", new object[] {
                        id_reserva,
                        destino,
                        fecha,
                        precio});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void insert_reservacionAsync(string id_reserva, string destino, string fecha, string precio) {
            this.insert_reservacionAsync(id_reserva, destino, fecha, precio, null);
        }
        
        /// <remarks/>
        public void insert_reservacionAsync(string id_reserva, string destino, string fecha, string precio, object userState) {
            if ((this.insert_reservacionOperationCompleted == null)) {
                this.insert_reservacionOperationCompleted = new System.Threading.SendOrPostCallback(this.Oninsert_reservacionOperationCompleted);
            }
            this.InvokeAsync("insert_reservacion", new object[] {
                        id_reserva,
                        destino,
                        fecha,
                        precio}, this.insert_reservacionOperationCompleted, userState);
        }
        
        private void Oninsert_reservacionOperationCompleted(object arg) {
            if ((this.insert_reservacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insert_reservacionCompleted(this, new insert_reservacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.practica2.com/insert_cliente", RequestNamespace="http://www.practica2.com", ResponseNamespace="http://www.practica2.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string insert_cliente(string id_cliente, string nombre_cliente, string fecha_nac, string tele_clien, string dir_cliente, string correo_cli) {
            object[] results = this.Invoke("insert_cliente", new object[] {
                        id_cliente,
                        nombre_cliente,
                        fecha_nac,
                        tele_clien,
                        dir_cliente,
                        correo_cli});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void insert_clienteAsync(string id_cliente, string nombre_cliente, string fecha_nac, string tele_clien, string dir_cliente, string correo_cli) {
            this.insert_clienteAsync(id_cliente, nombre_cliente, fecha_nac, tele_clien, dir_cliente, correo_cli, null);
        }
        
        /// <remarks/>
        public void insert_clienteAsync(string id_cliente, string nombre_cliente, string fecha_nac, string tele_clien, string dir_cliente, string correo_cli, object userState) {
            if ((this.insert_clienteOperationCompleted == null)) {
                this.insert_clienteOperationCompleted = new System.Threading.SendOrPostCallback(this.Oninsert_clienteOperationCompleted);
            }
            this.InvokeAsync("insert_cliente", new object[] {
                        id_cliente,
                        nombre_cliente,
                        fecha_nac,
                        tele_clien,
                        dir_cliente,
                        correo_cli}, this.insert_clienteOperationCompleted, userState);
        }
        
        private void Oninsert_clienteOperationCompleted(object arg) {
            if ((this.insert_clienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insert_clienteCompleted(this, new insert_clienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void insert_aerolineCompletedEventHandler(object sender, insert_aerolineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insert_aerolineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insert_aerolineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void insert_avionCompletedEventHandler(object sender, insert_avionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insert_avionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insert_avionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void insert_reservacionCompletedEventHandler(object sender, insert_reservacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insert_reservacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insert_reservacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void insert_clienteCompletedEventHandler(object sender, insert_clienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insert_clienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insert_clienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591